require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/invoice_historics", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # InvoiceHistoric. As you add validations to InvoiceHistoric, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InvoiceHistoric.create! valid_attributes
      get invoice_historics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      invoice_historic = InvoiceHistoric.create! valid_attributes
      get invoice_historic_url(invoice_historic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_invoice_historic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      invoice_historic = InvoiceHistoric.create! valid_attributes
      get edit_invoice_historic_url(invoice_historic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InvoiceHistoric" do
        expect {
          post invoice_historics_url, params: { invoice_historic: valid_attributes }
        }.to change(InvoiceHistoric, :count).by(1)
      end

      it "redirects to the created invoice_historic" do
        post invoice_historics_url, params: { invoice_historic: valid_attributes }
        expect(response).to redirect_to(invoice_historic_url(InvoiceHistoric.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InvoiceHistoric" do
        expect {
          post invoice_historics_url, params: { invoice_historic: invalid_attributes }
        }.to change(InvoiceHistoric, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post invoice_historics_url, params: { invoice_historic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested invoice_historic" do
        invoice_historic = InvoiceHistoric.create! valid_attributes
        patch invoice_historic_url(invoice_historic), params: { invoice_historic: new_attributes }
        invoice_historic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the invoice_historic" do
        invoice_historic = InvoiceHistoric.create! valid_attributes
        patch invoice_historic_url(invoice_historic), params: { invoice_historic: new_attributes }
        invoice_historic.reload
        expect(response).to redirect_to(invoice_historic_url(invoice_historic))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        invoice_historic = InvoiceHistoric.create! valid_attributes
        patch invoice_historic_url(invoice_historic), params: { invoice_historic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested invoice_historic" do
      invoice_historic = InvoiceHistoric.create! valid_attributes
      expect {
        delete invoice_historic_url(invoice_historic)
      }.to change(InvoiceHistoric, :count).by(-1)
    end

    it "redirects to the invoice_historics list" do
      invoice_historic = InvoiceHistoric.create! valid_attributes
      delete invoice_historic_url(invoice_historic)
      expect(response).to redirect_to(invoice_historics_url)
    end
  end
end
